### ISSUE TITLE
CTRL + RIGHT ARROW during text edition

### ISSUE THREAD

**Issue by sosite** [kenaniah/chrome-navigation-plugin#4]
HELLo moto ;)

During text editing I often use shortcuts `ctrl` + `left arrow` and `ctrl` + `right arrow` to move between whole words. Unfortunately your great plugin try to switch me then to the next page. Any chances to fix that? Change `ctrl` binding eg. to `ctrl` + `shift` or add simple settings, even in some kind of txt file?

**Comment by kenaniah** [comment]
Thanks for the bug report! My initial thought is to not attempt navigation when text selection / editing is taking place. I'll see about putting a patch together. 

Is there a specific website you would like me to test against to ensure everything works?

**Comment by sosite** [comment]
Great to hear that! Google docs is the site, where I am most irritate during writing :wink:

**Comment by kenaniah** [comment]
@sosite It turns out that `docs.google.com` actually does not use any sort of input fields and instead opted to redesign word processing in the browser from the ground up. To deal with this, I've added code to disable the extension on that site specifically in the new (8.4) release. Please let me know if you have any further issues. Thanks!

**Comment by sosite** [comment]
It looks good, thx for good work!
Unfortunatelly I found one more place when `CTRL + →` works unintentionally - in gmail during reply to an email. I think that it can take some more time to patch all websites with this particular bug so maybe you can just make this bug less frustrating? 😉 Much more often than simple `CTRL + →` I use `CTRL + SHIFT + →` shortcut so maybe you can detect additional `SHIFT` and then prevent from redirect to next screen?
